name: test-selenium-multi-browser-simultaneous
run-name: test-selenium-multi-browser-simultaneous-${{ github.run_number }}

on:
  schedule:
    - cron: '0 0 1 * *' # This workflow runs once a month

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, chrome]
      fail-fast: false
    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}
        options: --shm-size=2gb
        ports:
          - 4444:4444
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Cache pip packages
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install jq
        run: sudo apt-get install jq
      - name: Create and update config.json
        run: |
          echo '${{ vars.CONFIG_JSON }}' | jq --arg browser "${{ matrix.browser }}" '.selenium.browser = $browser' > config.json
      - name: Install dependencies
        run: |
          echo "Upgrading pip..."
          python -m pip install --upgrade pip
          echo "Installing requirements..."
          pip install -r requirements.txt
      - name: Run flake8 linting
        run: flake8 . --count --show-source --statistics
      - name: Run pytest with coverage and generate HTML report
        env:
          BROWSER: ${{ matrix.browser }}
        run: pytest -s --cov=./tests/selenium/test_selenium_pom.py tests/selenium/test_selenium_pom.py -v --html=tests-report.html --capture=sys --cov-report html  --cov-report term
      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report-${{ matrix.browser }}-${{ github.run_number }}
          path: |
            tests-report.html
            htmlcov/
            screenshots/
